name: tvdb_v4_dart
description: A Dart client for TheTVDB API v4. This is a direct translation of the official Python client.
version: 1.1.0
homepage: https://github.com/liperama-dev/tvdb-v4-dart

environment:
  sdk: ^3.9.0

dependencies:
  http: ^1.5.0
  dio: ^5.9.0
  meta: ^1.17.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  build_runner: ^2.7.0
  mocktail: ^1.0.4
  json_serializable: ^6.11.0
